/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisenosRouteImport } from './routes/disenos'
import { Route as SiluetasIdRouteImport } from './routes/siluetas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenosRoute = DisenosRouteImport.update({
  id: '/disenos',
  path: '/disenos',
  getParentRoute: () => rootRouteImport,
} as any)
const SiluetasIdRoute = SiluetasIdRouteImport.update({
  id: '/siluetas/$id',
  path: '/siluetas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disenos': typeof DisenosRoute
  '/siluetas/$id': typeof SiluetasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disenos': typeof DisenosRoute
  '/siluetas/$id': typeof SiluetasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disenos': typeof DisenosRoute
  '/siluetas/$id': typeof SiluetasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disenos' | '/siluetas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disenos' | '/siluetas/$id'
  id: '__root__' | '/' | '/disenos' | '/siluetas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisenosRoute: typeof DisenosRoute
  SiluetasIdRoute: typeof SiluetasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disenos': {
      id: '/disenos'
      path: '/disenos'
      fullPath: '/disenos'
      preLoaderRoute: typeof DisenosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siluetas/$id': {
      id: '/siluetas/$id'
      path: '/siluetas/$id'
      fullPath: '/siluetas/$id'
      preLoaderRoute: typeof SiluetasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisenosRoute: DisenosRoute,
  SiluetasIdRoute: SiluetasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
